version: 0.1.0
services:
  - type: web
    name: movie-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: API_KEY
        value: ac222af16cbc79455144e4bc946c4336
    pythonVersion: 3.11  
